name: master coverage

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.101
    - name: Install dependencies
      run: dotnet restore
    - name: Generate report for bizlogic aggregates test project
      run: |
        cd ./test/Server/BizLogic/Test.BizLogic.Aggregates
        dotnet test /p:CollectCoverage=true /p:CoverletOutput=TestResults/ /p:CoverletOutputFormat=lcov
    - name: Generate report for bizlogic abstractions test project
      run: |
        cd ./test/Server/BizLogic/Test.BizLogic.Abstractions
        dotnet test /p:CollectCoverage=true /p:CoverletOutput=TestResults/ /p:CoverletOutputFormat=lcov
    - name: Publish report for bizlogic aggregates test project
      uses: coverallsapp/github-action@master
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
        path-to-lcov: ./test/Server/BizLogic/Test.BizLogic.Aggregates/TestResults/coverage.info 
    - name: Publish report for bizlogic abstractions test project
      uses: coverallsapp/github-action@master
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
        path-to-lcov: ./test/Server/BizLogic/Test.BizLogic.Abstractions/TestResults/coverage.info 
